/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vocabularymaster.swing;

import com.mycompany.vocabularymaster.Entities.SeenWord;
import com.mycompany.vocabularymaster.utils.HibernateHandler;
import com.mycompany.vocabularymaster.utils.ResultEnum;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author papar
 */
public class GuessWordPanel extends javax.swing.JPanel {
    
    private String word;
    private SeenWord seenWord;
    private List<LetterComponent> letterComponents;

    /**
     * Creates new form GuessWordPanel
     * @param word
     */
    public GuessWordPanel(String word) {
        initComponents();
        this.word = word;
        this.seenWord = null;
        this.letterComponents = new ArrayList<>();
        printLetters();
        setInitialLetters();
    }
    
    public GuessWordPanel(SeenWord word) {
        initComponents();
        this.word = word.getWord();
        this.seenWord = word;
        this.letterComponents = new ArrayList<>();
        printLetters();
        setInitialLetters();
    }
    
    private int[] getIndexesToBeShown(){
        int quantityOfLetters = (int)Math.ceil(word.length()/3.0);
        var randomGenerator = new Random();
        int[] res;
        do{
            res = randomGenerator
                .ints(quantityOfLetters, 0, word.length())
                .distinct()
                .toArray();
        }while(res.length != quantityOfLetters);
        return res;
    }
    
    private void setInitialLetters(){
        var lettersToBeShown = getIndexesToBeShown();
        for(int i : lettersToBeShown)
            letterComponents.get(i).setAsInitialLetter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lettersPanel = new javax.swing.JPanel();
        forfeitButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        verifyButton = new javax.swing.JButton();

        mainLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mainLabel.setText("Guess the word");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lettersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lettersPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 43));
        jScrollPane1.setViewportView(lettersPanel);

        forfeitButton.setText("Forfeit");
        forfeitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forfeitButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(mainLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(forfeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forfeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setFinalScreen(String finalWords){
        forfeitButton.setEnabled(false);
        verifyButton.setEnabled(false);
        mainLabel.setText(finalWords);
        for(var letterComponent : letterComponents) letterComponent.setAsInitialLetter();
    }
    
    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        boolean isWordCorrect = true;
        for(var c : this.letterComponents) isWordCorrect = c.validateAnswer() && isWordCorrect;
        if(!isWordCorrect) return;
        setFinalScreen("You've guessed it!");
        if(seenWord == null) seenWord = new SeenWord(word, ResultEnum.GUESSED);
        else seenWord.updateWordData(ResultEnum.GUESSED);
        HibernateHandler.saveSeenWord(seenWord);
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        var frame = (JFrame) SwingUtilities.getRoot(this);
        var contentPane = frame.getContentPane();
        var cardLayout = (CardLayout) contentPane.getLayout();
        cardLayout.previous(contentPane);
        contentPane.remove(this);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void forfeitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forfeitButtonActionPerformed
        setFinalScreen("The answer was...");
        if(seenWord == null) seenWord = new SeenWord(word, ResultEnum.SURRENDERED);
        else seenWord.updateWordData(ResultEnum.SURRENDERED);
        HibernateHandler.saveSeenWord(seenWord);
    }//GEN-LAST:event_forfeitButtonActionPerformed

    private void printLetters(){
        for (char c : this.word.toCharArray()) {
            var letterComponent = new LetterComponent(c);
            this.lettersPanel.add(letterComponent);
            this.letterComponents.add(letterComponent);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton forfeitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lettersPanel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
