/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vocabularymaster.swing;

import com.mycompany.vocabularymaster.utils.ApiHandler;
import com.mycompany.vocabularymaster.utils.HibernateHandler;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author papar
 */
public class HomePagePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePagePanel
     */
    public HomePagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        learnVocabularyButton = new javax.swing.JLabel();
        reviseButton = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Vocabulary Master");

        learnVocabularyButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        learnVocabularyButton.setText("Learn new vocabulary");
        learnVocabularyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                learnVocabularyButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                learnVocabularyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                learnVocabularyButtonMouseExited(evt);
            }
        });

        reviseButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reviseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviseButton.setText("Revise");
        reviseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reviseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reviseButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reviseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(learnVocabularyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(learnVocabularyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reviseButton)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void learnVocabularyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnVocabularyButtonMouseEntered
        learnVocabularyButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        learnVocabularyButton.setForeground(Color.BLUE);
    }//GEN-LAST:event_learnVocabularyButtonMouseEntered

    private void learnVocabularyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnVocabularyButtonMouseExited
        learnVocabularyButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_learnVocabularyButtonMouseExited

    private void reviseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviseButtonMouseEntered
        reviseButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        reviseButton.setForeground(Color.BLUE);
    }//GEN-LAST:event_reviseButtonMouseEntered

    private void reviseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviseButtonMouseExited
        reviseButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_reviseButtonMouseExited

    private void learnVocabularyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnVocabularyButtonMouseClicked
        var frame = (JFrame) SwingUtilities.getRoot(this);
        var contentPane = frame.getContentPane();
        var cardLayout = (CardLayout) contentPane.getLayout();
        var word = ApiHandler.getRandomWord();
        contentPane.add(new GuessWordPanel(word));
        cardLayout.next(contentPane);
        frame.pack();
    }//GEN-LAST:event_learnVocabularyButtonMouseClicked

    private void reviseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviseButtonMouseClicked
        var frame = (JFrame) SwingUtilities.getRoot(this);
        var contentPane = frame.getContentPane();
        var cardLayout = (CardLayout) contentPane.getLayout();
        var word = HibernateHandler.getWordToRevise();
        if(word.isEmpty()) {
            JOptionPane.showMessageDialog(frame, "There isn't any words to revise today","Confirm message", JOptionPane.PLAIN_MESSAGE);
            
        }else{
            contentPane.add(new GuessWordPanel(word.get()));
            cardLayout.next(contentPane);
            frame.pack();
        }
    }//GEN-LAST:event_reviseButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel learnVocabularyButton;
    private javax.swing.JLabel reviseButton;
    // End of variables declaration//GEN-END:variables
}
