/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vocabularymaster.swing;

import java.awt.Color;

/**
 *
 * @author papar
 */
public class LetterComponent extends javax.swing.JPanel {
    
    private char letter;
    private boolean isCorrect;
    /**
     * Creates new form LetterComponent
     * @param letter
     */
    public LetterComponent(char letter) {
        initComponents();
        this.letter = letter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(30, 36));
        setMinimumSize(new java.awt.Dimension(30, 36));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setMaximumSize(new java.awt.Dimension(30, 30));
        jTextField1.setMinimumSize(new java.awt.Dimension(30, 30));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(30, 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(30, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if(jTextField1.isEditable()) jTextField1.setText("");
    }//GEN-LAST:event_jTextField1KeyTyped

    public boolean validateAnswer(){
        String lowerCaseGivenAnswer = jTextField1.getText().toLowerCase();
        String lowerCaseCorrectAnswer = Character.toString(this.letter).toLowerCase();
        if(lowerCaseGivenAnswer.equals(lowerCaseCorrectAnswer)){
            jTextField1.setBackground(Color.GREEN);
            jTextField1.setEditable(false);
            isCorrect = true;
        }else{
            jTextField1.setBackground(Color.RED);
            isCorrect = false;
        }
        return isCorrect;
    }
    
    public void setAsInitialLetter(){
        jTextField1.setText(Character.toString(letter));
        jTextField1.setBackground(Color.GREEN);
        jTextField1.setEditable(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
